server:
  port: 8098    #default port where the service will be started

spring:    
  application:
    name: product-service   #current service name to be used by the eureka server
  sleuth:
    sampler:
      probability: 1.0
    web:
      skipPattern: (^cleanup.*)
  zipkin:
    base-url: http://localhost:9411/
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.
 
logging:
  level:
    com.microservices.skillnet: DEBUG
